# Licedsed to the Creative Commons Attribution 4.0 International License (CC BY 4.0)
#
# http://creativecommons.org/licenses/by/4.0/
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# refer to based on: https://awesome-prometheus-alerts.grep.to/rules
#
groups:
  # see: https://github.com/Lusitaniae/apache_exporter
  - name: lusitaniae-apache.alerting-prometheus.io
    rules:
    - alert: ApacheDown
      expr: apache_up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Apache down (instance {{ $labels.instance }})
        description: "Apache down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: ApacheWorkersLoad
      expr: (sum by (instance) (apache_workers{state="busy"}) / sum by (instance) (apache_scoreboard) ) * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Apache workers load (instance {{ $labels.instance }})
        description: "Apache workers in busy state approach the max workers count 80% workers busy on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: ApacheRestart
      expr: apache_uptime_seconds_total / 60 < 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Apache restart (instance {{ $labels.instance }})
        description: "Apache has just been restarted.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
